spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    properties:
      auto.register.schemas: true
      use.latest.version: true


    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: foo_group
      auto-offset-reset: latest


server:
  port: 8082